// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1Pdx0hcS3r4hN7M9jo1g45NyzcqFwYw',
    appId: '1:985871772298:web:a78e40f2484ddd38b99b73',
    messagingSenderId: '985871772298',
    projectId: 'skillswap-ad93c',
    authDomain: 'skillswap-ad93c.firebaseapp.com',
    storageBucket: 'skillswap-ad93c.appspot.com',
    measurementId: 'G-HFVQGVSXK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdl8k4gYxSMET1ZeYU-fD1vL1l-GPPrb8',
    appId: '1:985871772298:android:ccb731d677790cceb99b73',
    messagingSenderId: '985871772298',
    projectId: 'skillswap-ad93c',
    storageBucket: 'skillswap-ad93c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUbxPeIDwXdrMjeOjMyiyTz8GAPdv7LBs',
    appId: '1:985871772298:ios:1599555b55bf2114b99b73',
    messagingSenderId: '985871772298',
    projectId: 'skillswap-ad93c',
    storageBucket: 'skillswap-ad93c.appspot.com',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUbxPeIDwXdrMjeOjMyiyTz8GAPdv7LBs',
    appId: '1:985871772298:ios:0112af019fa997e5b99b73',
    messagingSenderId: '985871772298',
    projectId: 'skillswap-ad93c',
    storageBucket: 'skillswap-ad93c.appspot.com',
    iosBundleId: 'com.example.skillswap.RunnerTests',
  );
}
